# Generated by Django 5.0.1 on 2024-01-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
